### ISSUE TITLE
Fluidd Broken

### ISSUE THREAD

**Issue by Quotacious** [midikeyboard/dark-acryl-fluidd-mainsail-theme#1]
This dark theme is unfortunately very bright in Fluidd! 😆 

![image](https://github.com/midikeyboard/dark-acryl-fluidd-mainsail-theme/assets/5301311/9e2315d8-e11d-40c5-a2c2-7b04ab213ac0)

**Comment by midikeyboard** [comment]
i'm sorry i was unaware of this issue... have you enabled the dark mode toggle in UI settings? this is the cause for these issues in mainsail. i sadly do not run fluidd so cannot confirm this...

edit: asked a community member to confirm this on fluidd's end. and the behaviour is the same. 
i have also updated the readme to inform users of this requirement.

thanks for notifying me
