### ISSUE TITLE
The animation is changing the height of the page

### ISSUE THREAD

**Issue by voidtrance** [midikeyboard/dark-acryl-fluidd-mainsail-theme#2]
The animated circles seem to be changing the height of the page, which ends up moving the scrollbar around. This can cause the page to move with certain positions. The same issue is present with the vibrant-acryl theme but on that repo, issues are disabled.

**Comment by midikeyboard** [comment]
My apologies for the late response! i have implemented the fix and it should now not occur in either one of the themes. also thank you for letting me know about closed issues. i have opened them :)

PR fixing this:
https://github.com/midikeyboard/vibrant-acryl-fluidd-mainsail-theme/pull/5
